version: '3.9'

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  backend:
    container_name: backend 
    build: ./backend 
    image: backend 
    command: ash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "5000:3000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address:
          '172.20.0.3'

  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    command: "yarn dev"
    volumes:
      - ./frontend:/app/
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address:
          '172.20.0.4'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24


